services:
  postgres:
    image: postgres:15-alpine
    container_name: db
    command: -p ${POSTGRES_PORT:-5433}
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-user}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-password}
      POSTGRES_DB: ${POSTGRES_DB:-bswdb}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER:-user} -p ${POSTGRES_PORT:-5433}"]
      interval: 10s
      timeout: 5s
      retries: 5
    restart: unless-stopped

  app:
    build:
      context: ..
      dockerfile: Dockerfile
    container_name: bsw
    environment:
      DSN: postgres://${POSTGRES_USER:-user}:${POSTGRES_PASSWORD:-password}@postgres:${POSTGRES_PORT:-5433}/${POSTGRES_DB:-bswdb}?sslmode=disable
      PGUSER: ${POSTGRES_USER:-user}
      PGPASSWORD: ${POSTGRES_PASSWORD:-password}
      PGDATABASE: ${POSTGRES_DB:-bswdb}
      PGPORT: ${POSTGRES_PORT:-5433}
      PGHOST: postgres
    depends_on:
      postgres:
        condition: service_healthy
    restart: unless-stopped

  frontend:
    build:
      context: ..
      dockerfile: Dockerfile.frontend
    container_name: bsw-frontend
    environment:
      API_BASE: http://app:8080
    depends_on:
      - app
    restart: unless-stopped

  caddy:
    build:
      context: ..
      dockerfile: cloud/Dockerfile.caddy
    container_name: bsw-caddy
    restart: unless-stopped
    environment:
      DOMAIN: ${DOMAIN}
      CF_API_TOKEN: ${CF_API_TOKEN}
    ports:
      - "80:80"
      - "443:443"
      - "443:443/udp"
    depends_on:
      - frontend
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile:ro
      - caddy_data:/data
      - caddy_config:/config

volumes:
  postgres_data:
  caddy_data:
  caddy_config:
